name: Do Not Merge
on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  do-not-merge:
    # contains(search, item) is not case-sensitive
    # Therefore 'Do Not Merge' and 'DO NOT MERGE' will also match
    # see https://docs.github.com/en/actions/learn-github-actions/expressions#contains
    if: contains(github.event.pull_request.labels.*.name, 'do not merge')
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: fail if label exists
        run: |
          echo "This PR has the label 'do not merge'."
          exit 1
