name: YAMLlint

on:
  workflow_call:
    inputs:
      action-name:
        default: "yamllint / yamllint"
        required: false
        type: string
      target-path:
        default: "."
        required: false
        type: string

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Lint and Annotate
        uses: staffbase/yamllint-action@f607dae290ba419436173cc364051db98ac8d805 # v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          action-name: ${{ inputs.action-name }}
          target-path: ${{ inputs.target-path }}
