name: SonarCloud
on:
  workflow_call:
    inputs:
      path:
        type: string
        required: true
    secrets:
      token:
        required: true
      sonar_token:
        required: true

jobs:
  sonarcloud:

    name: Analyze branch
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}
          fetch-depth: 0

      - name: Cache Coverage Data
        uses: actions/cache@v3.0.2
        with:
          path: ${{ inputs.path }}
          key: ${{ runner.os }}-coverage-data

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          SONAR_TOKEN: ${{ secrets.sonar_token }}
