name: Changeset Release

on:
  workflow_call:
    inputs:
      node-version-file:
        default: '.nvmrc'
        required: false
        type: string
      publish-script:
        default: 'pnpm release'
        required: false
        type: string
      version-script:
        default: 'pnpm changeset version'
        required: false
        type: string
      node-registry:
        required: false
        type: string
      node-registry-scope:
        required: false
        type: string
    secrets:
      app_id:
        required: true
      private_key:
        required: true
      npm-token:
        required: true

jobs:
  release:
    name: changeset-release
    runs-on: ubuntu-slim
    permissions:
      contents: read
    steps:
      - name: Get App Token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        id: get_token
        with:
          app-id: ${{ secrets.app_id }}
          private-key: ${{ secrets.private_key }}

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: ${{ steps.get_token.outputs.token }}

      - name: Setup PNPM
        uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb # v6.0.0

      - name: Setup Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ${{ inputs.node-version-file }}
          cache: 'pnpm'
          registry-url: ${{ inputs.node-registry }}
          scope: ${{ inputs.node-registry-scope }}

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@e4156907cdd269dcaa37f03263be504a3570994d # v1.6.0
        with:
          commit: 'chore(release): Bump package version'
          title: '📦 Release New Version'
          createGithubReleases: true
          version: ${{ inputs.version-script }}
          publish: ${{ inputs.publish-script }}
        env:
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
          HOME: ${{ github.workspace }}
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
