name: Backstage Entity Validation

on:
  workflow_call:
    inputs:
      path:
        default: "catalog-info.yaml"
        required: false
        type: string
      custom-schema-url:
        default: https://raw.githubusercontent.com/Staffbase/gha-workflows/refs/heads/main/schemas/custom-catalog-info.schema.json
        required: false
        type: string

jobs:
  validation:
    name: Validate Backstage Entities
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Download the schema file
      - name: Download custom schema file
        if: ${{ inputs.custom-schema-url }} != ""
        run: |
          curl -o custom-catalog-info.schema.json ${{ inputs.custom-schema-url }}
          # Set the schema file location
          echo "schema-file-location=custom-catalog-info.schema.json" >> $GITHUB_OUTPUT

      - name: Validate Backstage Entities
        uses: RoadieHQ/backstage-entity-validator@v0.5.0
        with:
          path: ${{ inputs.path }}
          validationSchemaFileLocation: custom-catalog-info.schema.json
