name: Release Drafter

on:
  workflow_call:
    inputs:
      config-name:
        required: false
        type: string
        default: "release-drafter.yml"
      name:
        required: false
        type: string
      publish:
        default: false
        required: false
        type: boolean
      tag:
        required: false
        type: string
      version:
        required: false
        type: string
      prerelease:
        required: false
        type: boolean
        default: false
      prerelease-identifier:
        required: false
        type: string
        default: ""
    secrets:
      token:
        required: false
      client_id:
        required: false
      private_key:
        required: false

jobs:
  update_release_draft:
    name: update release draft
    runs-on: ubuntu-slim
    permissions:
      contents: write
      pull-requests: read

    env:
      USING_APP_CREDENTIALS: ${{ secrets.client_id != '' && secrets.private_key != '' }}

    steps:
      - name: Get App Token
        if: ${{ env.USING_APP_CREDENTIALS == 'true' }}
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: get_token
        with:
          client-id: ${{ secrets.client_id }}
          private-key: ${{ secrets.private_key }}

      - name: Update Release
        uses: release-drafter/release-drafter@ed4bc48ec97379be2258e7b7ac2624a3e26ab809 # v7.4.0
        with:
          config-name: ${{ inputs.config-name }}
          name: ${{ inputs.name }}
          publish: ${{ inputs.publish }}
          tag: ${{ inputs.tag }}
          version: ${{ inputs.version }}
          prerelease: ${{ inputs.prerelease }}
          prerelease-identifier: ${{ inputs.prerelease-identifier }}
        env:
          GITHUB_TOKEN: ${{ env.USING_APP_CREDENTIALS == 'true' && steps.get_token.outputs.token || secrets.token }}
