name: Changeset Release

on:
  workflow_call:
    inputs:
      commit-msg:
        required: false
        type: string
        default: "chore(release): Bump package version"
      pr-title:
        required: false
        type: string
        default: "📦 Release"
      publish-script:
        required: true
        type: string
      version-script:
        required: true
        type: string
    secrets:
      npm_token:
        required: false
      app_id:
        required: false
      private_key:
        required: false

jobs:
  changeset-release:
    name: changeset-release
    runs-on: ubuntu-24.04
    steps:
      - name: Get App Token
        uses: actions/create-github-app-token@v1.11.0
        id: get_token
        with:
          app-id: ${{ secrets.app_id }}
          private-key: ${{ secrets.private_key }}

      - name: Publish release
        uses: changesets/action@v1
        with:
          commit: ${{ inputs.commit-msg }}
          title: ${{ inputs.pr-title }}
          setupGitUser: true
          createGithubReleases: true
          publish: ${{ inputs.publish-script }}
          version: ${{ inputs.version-script}}
        env:
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
          NPM_TOKEN: ${{ secrets.npm_token }}
