name: Changeset Release

on:
  workflow_call:
    inputs:
      node-version-file:
        default: '.nvmrc'
        required: false
        type: string
      publish-script:
        default: 'pnpm release'
        required: false
        type: string
      version-script:
        default: 'pnpm changeset version'
        required: false
        type: string
      node-registry:
        required: false
        type: string
      node-registry-scope:
        required: false
        type: string
    secrets:
      app_id:
        required: true
      private_key:
        required: true
      npm-token:
        required: true

jobs:
  release:
    name: changeset-release
    runs-on: ubuntu-24.04
    steps:
      - name: Get App Token
        uses: actions/create-github-app-token@v2.1.0
        id: get_token
        with:
          app-id: ${{ secrets.app_id }}
          private-key: ${{ secrets.private_key }}

      - name: Checkout
        uses: actions/checkout@v5
        with:
          token: ${{ steps.get_token.outputs.token }}

      - name: Setup PNPM
        uses: pnpm/action-setup@v4.2.0

      - name: Setup Node
        uses: actions/setup-node@v6.0.0
        with:
          node-version-file: ${{ inputs.node-version-file }}
          cache: 'pnpm'
          registry-url: ${{ inputs.node-registry }}
          scope: ${{ inputs.node-registry-scope }}

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}

      - name: Create Release Pull Request
        id: changesets
        uses: changesets/action@v1.5.2
        with:
          commit: 'chore(release): Bump package version'
          title: '📦 Release New Version'
          createGithubReleases: true
          version: ${{ inputs.version-script }}
          publish: ${{ inputs.publish-script }}
        env:
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
          HOME: ${{ github.workspace }}
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}
