name: TestIO - Trigger Test

on:
  workflow_call:
    inputs:
      testio-slug:
        required: false
        type: string
        default: 'staffbase'
      testio-product-id:
        required: true
        type: string
    secrets:
      github-token:
        required: true
      testio-token:
        required: true

env:
  TESTIO_SCRIPTS_DIR: .github/scripts/testio

jobs:
  testio-trigger-test:

    name: TestIO - Trigger Test
    runs-on: ubuntu-22.04

    steps:
      - name: TestIO - Checkout folder with required resources from gha-workflows
        uses: actions/checkout@v3
        with:
          repository: Staffbase/gha-workflows
          ref: 'testio-trigger-template'                        # TODO to be removed when merged
          token: ${{ secrets.github-token }}
          sparse-checkout: ${{ env.TESTIO_SCRIPTS_DIR }}        # only checkout this folder

      - name: TestIO - Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: TestIO - Install Dependencies
        run: |
          cd ${{ env.TESTIO_SCRIPTS_DIR }}
          npm install

      - name: TestIO - Add PR comment for requesting required input
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TESTIO_SCRIPTS_DIR: ${{ env.TESTIO_SCRIPTS_DIR }}
        run: npx ts-node ${{ env.TESTIO_SCRIPTS_DIR }}/addPRcomment.ts
