name: TestIO - Trigger Test

on:
  workflow_call:
    inputs:
      testio-slug:
        required: false
        type: string
        default: 'staffbase'
      testio-product-id:
        required: true
        type: string
    secrets:
      github-token:
        required: true
      testio-token:
        required: true

env:
  TESTIO_SCRIPTS_DIR: .github/scripts/testio

jobs:
  testio-trigger-test:

    name: TestIO - Trigger Test
    runs-on: ubuntu-22.04
    if: startsWith(github.event.comment.body, '@bot-testio exploratory-test')     # this is the prefix of all subsequent comments

    steps:
      - name: TestIO - Checkout folder with required resources from gha-workflows
        uses: actions/checkout@v3
        with:
          repository: Staffbase/gha-workflows
          ref: 'testio-trigger-template'                        # TODO to be removed when merged
          token: ${{ secrets.github-token }}
          sparse-checkout: ${{ env.TESTIO_SCRIPTS_DIR }}        # only checkout this folder

      - name: TestIO - Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: TestIO - Install Dependencies
        run: |
          cd ${{ env.TESTIO_SCRIPTS_DIR }}
          npm install

      - name: TestIO - Add PR comment for requesting required input
        id: prepare
        if: startsWith(github.event.comment.body, '@bot-testio exploratory-test create')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TESTIO_SCRIPTS_DIR: ${{ env.TESTIO_SCRIPTS_DIR }}
          TESTIO_CREATE_COMMENT_URL: ${{ github.event.comment.html_url }}
        run: npx ts-node ${{ env.TESTIO_SCRIPTS_DIR }}/addPRcomment.ts

      - name: TestIO - Retrieve input and create payload
        id: payload
        if: startsWith(github.event.comment.body, '@bot-testio exploratory-test submit')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TESTIO_SCRIPTS_DIR: ${{ env.TESTIO_SCRIPTS_DIR }}
          TESTIO_SUBMIT_COMMENT_ID: ${{ github.event.comment.id }}
        run: npx ts-node ${{ env.TESTIO_SCRIPTS_DIR }}/retrievePayload.ts
